"""initial schema

Revision ID: 447243cda2a3
Revises: 
Create Date: 2026-07-13 19:09:45.325468

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '447243cda2a3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('address_validations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('building_name', sa.String(length=255), nullable=True),
    sa.Column('street_address', sa.String(length=255), nullable=False),
    sa.Column('suburb', sa.String(length=120), nullable=True),
    sa.Column('city', sa.String(length=120), nullable=False),
    sa.Column('post_code', sa.String(length=32), nullable=True),
    sa.Column('country_code', sa.String(length=8), nullable=False),
    sa.Column('original_payload_json', sa.Text(), nullable=False),
    sa.Column('corrected_payload_json', sa.Text(), nullable=False),
    sa.Column('validation_status', sa.String(length=20), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('provider_name', sa.String(length=40), nullable=False),
    sa.Column('provider_reference', sa.String(length=120), nullable=True),
    sa.Column('validated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('address_validations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_address_validations_validated_at'), ['validated_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_address_validations_validation_status'), ['validation_status'], unique=False)

    op.create_table('execution_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trigger_type', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('total_duration_ms', sa.Integer(), nullable=False),
    sa.Column('total_urls', sa.Integer(), nullable=False),
    sa.Column('success_count', sa.Integer(), nullable=False),
    sa.Column('failed_count', sa.Integer(), nullable=False),
    sa.Column('overall_status', sa.String(length=20), nullable=False),
    sa.Column('initiated_by', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('execution_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_execution_history_started_at'), ['started_at'], unique=False)

    op.create_table('monitored_urls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('monitored_urls', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_monitored_urls_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_monitored_urls_url'), ['url'], unique=True)

    op.create_table('execution_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('execution_history_id', sa.Integer(), nullable=False),
    sa.Column('monitored_url_id', sa.Integer(), nullable=False),
    sa.Column('dns_resolved', sa.Boolean(), nullable=False),
    sa.Column('http_status_code', sa.Integer(), nullable=True),
    sa.Column('https_valid', sa.Boolean(), nullable=False),
    sa.Column('response_time_ms', sa.Integer(), nullable=True),
    sa.Column('availability_status', sa.String(length=10), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('checked_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['execution_history_id'], ['execution_history.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['monitored_url_id'], ['monitored_urls.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('execution_details', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_execution_details_availability_status'), ['availability_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_execution_details_execution_history_id'), ['execution_history_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_execution_details_monitored_url_id'), ['monitored_url_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('execution_details', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_execution_details_monitored_url_id'))
        batch_op.drop_index(batch_op.f('ix_execution_details_execution_history_id'))
        batch_op.drop_index(batch_op.f('ix_execution_details_availability_status'))

    op.drop_table('execution_details')
    with op.batch_alter_table('monitored_urls', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_monitored_urls_url'))
        batch_op.drop_index(batch_op.f('ix_monitored_urls_is_active'))

    op.drop_table('monitored_urls')
    with op.batch_alter_table('execution_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_execution_history_started_at'))

    op.drop_table('execution_history')
    with op.batch_alter_table('address_validations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_address_validations_validation_status'))
        batch_op.drop_index(batch_op.f('ix_address_validations_validated_at'))

    op.drop_table('address_validations')
    # ### end Alembic commands ###
